### ISSUE TITLE
Binaries were not uploaded to the channel

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/nco-feedstock#15]
After the merge of #14 the binaries were note uploaded to the channel.

**Comment by jakirkham** [comment]
So, it did upload for OS X. It just didn't upload for Linux. Not sure why the latter is not working.

**Comment by jakirkham** [comment]
@pelson, could you please help look into this? It seems we have another case of uploads not happening. While these cases are largely quite rare, there still seem to be a couple of them. It's a little concerning.

**Comment by jakirkham** [comment]
Yeah, this is more like `erlang`. I had a similar issue with `libarchive`. By disabling `make check`, it [fixed]( https://github.com/conda-forge/libarchive-feedstock/issues/3#issuecomment-227556577 ) the problem. Now `make check` wasn't failing so I don't know why this mattered. However, I have ended up having to leave it out as a result. Maybe a similar solution will work here?

**Comment by ocefpaf** [comment]
Fixed in #20
