### ISSUE TITLE
Rebuild for netcdf 4.9.0?

### ISSUE THREAD

**Issue by zklaus** [conda-forge/nco-feedstock#157]
### Comment:

Should we do a rebuild for netcdf 4.9.0? I am salivating over some of the compression options.

**Comment by xylar** [comment]
I believe we won't be able to.  I think we will need migration of dependencies.  We are waiting on 4.9.1 to be released because 4.9.0 was heavily patched.  See https://github.com/conda-forge/libnetcdf-feedstock/pull/140#issuecomment-1262836839
