### ISSUE TITLE
nco and gsl compatability issues

### ISSUE THREAD

**Issue by ColemanTom** [conda-forge/nco-feedstock#176]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

NCO 5.1.6 requires libgsl.so.25, but gsl 2.7.1 does not contain that anymore, it includes libgsl.so.27 only. I think if you pin the version to be `gsl <2.7.1` it should be safe. Note `gsl==2.7.1` is only available from the [anaconda channel](https://anaconda.org/anaconda/gsl/files?version=2.7.1).

### Installed packages

```shell
See above, install nco==5.1.6 and gsl==2.7.1
```

### Environment info

```shell
I am not allowed to.
```

**Comment by xylar** [comment]
@ColemanTom, unfortunately, mixing packages from `main` and `conda-forge` channels doesn't work well and is not considered to be safe for the reasons you have discovered.  The preferred solution is:
https://conda-forge.org/#about
```
conda config --add channels conda-forge
conda config --set channel_priority strict
```
This will ensure that both `nco` and `gsl` come from conda-forge.  Even when we build `gsl==2.7.1` for conda-forge, it should work fine for NCO.

**Comment by xylar** [comment]
With the settings above, when I try:
```
$ mamba create -y -n test "nco=5.1.6" "gsl=2.7.1"
```
I see (as expected):
```
Could not solve for environment specs
The following package could not be installed
└─ gsl 2.7.1**  is uninstallable because it conflicts with any installable versions previously reported.
```

**Comment by ColemanTom** [comment]
Thanks for the advice. I'm in an air gapped environment with config largely controlled by admins. The solver is flexible, I'm not sure why, but I've requested they add `custom_channels` into the config to alias conda-forge to our local mirror, that way we can at least specify `conda-forge::gsl` to force gsl to come from there instead of the default.

I'll close this. Thanks again for the suggestions.
