### ISSUE TITLE
NCO libjpeg dependency problem

### ISSUE THREAD

**Issue by yingkaisha** [conda-forge/nco-feedstock#30]
Hi,

I have installed the nco 4.6.5-0 from `conda install -c conda-forge nco` and when I was trying to use command like `ncea`, I got the error as: 

`dyld: Library not loaded: @rpath/libjpeg.9.dylib
  Referenced from: /Users/myname/anaconda2/bin/ncea
  Reason: image not found
Abort trap: 6` 

I have `jpeg` been updated in conda and can find a whole set of libjpeg in /opt/local/.... Is there anything I can do to fix the problem ?

**Comment by ocefpaf** [comment]
It seems you have the usual "mixed channel" problem. Please take a look at

http://conda-forge.github.io/docs/conda-forge_gotchas.html#using-multiple-channels

and let me know if that fixes the problem for you.

**Comment by yingkaisha** [comment]
I've added `.condarc` in my home dir with

`channels:
  - conda-forge
  - defaults`

Then uninstall and install `nco` again, refresh the bash, but doesn't seem to be working, the error msg is the same.

**Comment by yingkaisha** [comment]
After I did `conda update --all` to re-arange all the versions, the problem disappeared. Thanks for the help.
