### ISSUE TITLE
Reproducable docker build?

### ISSUE THREAD

**Issue by kwilcox** [conda-forge/nco-feedstock#34]
@conda-forge/nco Does anyone have a Dockerfile to build a stable NCO 4.6.6 environment with all the goodies?

I'm seeing lots of data corruption when testing an update to `4.6.6` from `4.6.1` I want to make sure its not an issue with the conda build before investigating further.

**Comment by kwilcox** [comment]
AH, nevermind. I was masking the actual error elsewhere.

```
ERROR NC_ELATEFILL (formerly NC_EFILLVALUE) Attempt to define fill value when data already exists
HINT: NC_ELATEFILL errors can occur when ncap2 attempts to define a variable with a _FillValue attribute in a netCDF4 file.  We believe this is an NCO bug (fxm TODO nco1089) and are working to fix it. Does your output file need to be netCDF4 or netCDF4_classic format? If so, then wait for us to fix the bug. If not, change the output format to netCDF3 (e.g., with -3 option) as a temporary workaround. This file can then successfully be converted to netCDF4 (e.g., with ncks -4 in.nc out.nc).
nco_err_exit(): ERROR Short NCO-generated message (usually name of function that triggered error): nco_put_att()
nco_err_exit(): ERROR Error code is -122. Translation into English with nc_strerror(-122) is "NetCDF: Attempt to define fill value when data already exists."
nco_err_exit(): ERROR NCO will now exit with system call exit(EXIT_FAILURE)
```

I'll just stick to 4.6.1 for now.

**Comment by Mirce-UNAM** [comment]
Excuse me...did you find the solution to your error?. I am having the same error, but I am using the version 4.7.2

**Comment by kwilcox** [comment]
If you are getting the `Attempt to define fill value when data already exists` error message the solution is listed in the error message and also in my comment above.

**Comment by czender** [comment]
Also be sure you compile against netCDF 4.6.0 or later since there were some _FillValue regressions attributable to netCDF 4.5.x libraries.

**Comment by ocefpaf** [comment]
> Also be sure you compile against netCDF 4.6.0 or later since there were some _FillValue regressions attributable to netCDF 4.5.x libraries.

We are not using netCDF 4.6.0 yet on conda-forge. I'll send PRs to test that version.

**Comment by Mirce-UNAM** [comment]
Thank you very much kwilcox and czender...I am sorry I didn't see before the solution in kwilcox message.
I just converted my file to netcdf3 and it worked, so then I'll turn it back to netcdf4 ... Just one last question, this bug is still on the 4.7.2 version? Thanks!
