### ISSUE TITLE
HTTP Error While Trying To Install NCO

### ISSUE THREAD

**Issue by jdrenken** [conda-forge/nco-feedstock#38]
Hello all,

I was pointed to this amazing Anaconda python option due to the need of combining multiple netCDF daily climo files.  I have the conda-forge channel enabled, but receive this error continously while attempting to install nco.

CondaHTTPError: HTTP None None for url <https://conda.anaconda.org/conda-forge/win-64/repodata.json>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),),)

**Comment by ocefpaf** [comment]
Looks like you are trying to install conda-forge's `nco` on Windows. Unfortunately we don't provide a binary for that platform yet.
