### ISSUE TITLE
OSX conda package not building with NCO 4.6.9?

### ISSUE THREAD

**Issue by czender** [conda-forge/nco-feedstock#42]
@doutriaux1 reports that OSX conda package is not available despite Linux package having been available for a day. The build-status indicator for both is green on the nco-feedstock homepage. Is that a false-negative for OSX? Not sure where/if the build logs are saved so it's hard for me to tell whether there's an error. FWIW I have received build failures with clang since ~Sep 4 when Travis updated to new Ubuntu Trusty. Problem there appears to be due to unresolved OpenMP symbols, e.g., "unresolved resolved reference to __kmpc_end_single". It appears that configure.sh uses g++ to link ncap2, even when it uses CXX=clang to compile it. Possibly the newer clang inserts OpenMP symbols into ncap2 and thus needs a different linker (is clang also a linker?) or simply needs to be linked to another library (e.g., -lomp) on OSX now that clang supports OpenMP. Any help appreciated with the OSX conda or upstream Travis clang builds of NCO. Alerting @xylar and @ocefpaf to this issue.

**Comment by ocefpaf** [comment]
> @doutriaux1 reports that OSX conda package is not available despite Linux package having been available for a day.

Travis-CI, which builds our OS X packages, is having trouble. See https://www.traviscistatus.com/incidents/h6gwvyq9zky0

and if you want to follow the build check https://travis-ci.org/conda-forge/nco-feedstock/builds/277263541

> The build-status indicator for both is green on the nco-feedstock homepage. Is that a false-negative for OSX? 

Not really, it is probably reflecting the last build.

> Not sure where/if the build logs are saved so it's hard for me to tell whether there's an error. 

They are all in the CIs logs at https://travis-ci.org/conda-forge/nco-feedstock

> FWIW I have received build failures with clang since ~Sep 4 when Travis updated to new Ubuntu Trusty.

conda-forge uses a CentOS 6 docker image to build Linux using CircleCI. We only use Travis-CI for OS X, so we are not affected. But thanks for letting us know!

> Any help appreciated with the OSX conda or upstream Travis clang builds of NCO.

Not sure what you mean. In conda-forge we do build OS X pkgs with clang by default but not with OpenMP though, we should look into that.
