### ISSUE TITLE
Windows builds are broken for 4.7.2

### ISSUE THREAD

**Issue by pedro-vicente** [conda-forge/nco-feedstock#58]
I replaced the name of the option
 NCO_MSVC_USE_MT
to
MSVC_USE_STATIC_CRT

to keep it consistent with the name used by the other libraries

there are 2 new scripts in /cmake

` clone.bat`

git clones all the dependencies

`
bld.bat`

builds NCO

you can see bld.bat for the CMake options used

`bld.bat crt`

with crt as option builds static CRT version (Debug Win64)

**Comment by ocefpaf** [comment]
I renamed this issue to reflect the problems we encounter in https://github.com/conda-forge/nco-feedstock/pull/57

**Comment by xylar** [comment]
Can we close this issue once we see are sure that 4.7.3 is working with Windows? (See #59.)

**Comment by ocefpaf** [comment]
Yep. Thanks @xylar!
