### ISSUE TITLE
Appveyor failed on 4.3.7 (with HDF5 1.10.1)

### ISSUE THREAD

**Issue by xylar** [conda-forge/nco-feedstock#62]
It looks like Appveyor didn't work on the latest merge to master:
https://github.com/conda-forge/nco-feedstock/commits/master
https://ci.appveyor.com/project/conda-forge/nco-feedstock/build/1.0.64
```
...
C:\projects\nco-feedstock\recipe: C2122 Found invalid license family "GPL-3.0"
C:\projects\nco-feedstock\recipe: C2124 Found file "data/in.cdl" in meta.yaml that doesn't exist
Command exited with code 1
```

Anyone know what went wrong?

We currently have a windows build of 4.3.7 with hdf5 1.8.18 but not with hdf5 1.10.1, so I think we do want to figure this out.

**Comment by ocefpaf** [comment]
Re-starting should fix that. That is conda-verify, which we pulled from the channel, unrelated to the PR.

**Comment by xylar** [comment]
Great! I'm glad this is easy to fix with a restart!

**Comment by ocefpaf** [comment]
Thanks bringing that to our attention. I missed that completely when I merged it!
