### ISSUE TITLE
AppVeyor window build of 4.7.6 is failing

### ISSUE THREAD

**Issue by xylar** [conda-forge/nco-feedstock#72]
See:
https://github.com/conda-forge/nco-feedstock/pull/71
https://ci.appveyor.com/project/conda-forge/nco-feedstock/build/1.0.98

I have no experience with building NCO for windows so I'm not able to make a more insightful comment, I'm afraid.

I am going to merge #71  anyway so at least the linux and OSX builds of 4.7.6 will be available.

**Comment by xylar** [comment]
I would note that AppVeyor was able to successfully build NCO from its own repo:
https://ci.appveyor.com/project/czender/nco/build/1.0.460

**Comment by czender** [comment]
Thanks @xylar. The fatal error was that a non-void function did not return a value at all. This has been fixed in the latest snapshot, 4.7.7-alpha01. Strange that it built on Appveyor "from its own repo" but not here. I don't understand the intracacies of Appveyor. Anyway, the fix needed by Windows is in the current snapshot. Not sure how to deal with that to get a 4.7.6 build on Windows.

**Comment by xylar** [comment]
To be honest, I think the easiest solution is to wait for a 4.7.7 release and cope with the fact that 4.7.6 was broken for Windows.

**Comment by xylar** [comment]
If the issue had been a dependency or something like that, it would have made sense to try to fix it here instead.

**Comment by czender** [comment]
Agreed. It's just weird that we use Appveyor to avoid this situation, i.e., broken builds, and it never warned us during the development process that anything was wrong.

**Comment by ocefpaf** [comment]
> Agreed. It's just weird that we use Appveyor to avoid this situation, i.e., broken builds, and it never warned us during the development process that anything was wrong.

BTW, it is not the same failure but AppVeyor is returning a false positive on the main repo: https://ci.appveyor.com/project/czender/nco/build/1.0.437#L1020

I'll take a look later today to check what is going on there.
