### ISSUE TITLE
Installing nco breaks spyder

### ISSUE THREAD

**Issue by hadfieldnz** [conda-forge/nco-feedstock#73]
On a newly-installed Anaconda 5.2.0 for Windows, I did the following from the Anaconda Prompt in the base environment.
  
  1. Append conda-forge to the channels list with: conda config --append channels conda-forge.

  2. Update all conda packages with: conda update --all. Conda is now at 4.5.10, Python at 3.6.6 and Spyder at 3.3.1.

  3. Check the operation of Spyder with: python -c "from spyder.app.start import main; main()". Spyder functions OK.

  4. Install a bunch of other packages with: conda install xarray eofs cartopy netcdf4. Check Spyder as before; it functions OK.

  5. Install nco with: conda install nco. Conda takes 5 or more minutes to solve the environment (much longer than the previous install command) and then offers to install a few new packages, but also to replace some 36 packages from the defaults channel with other, mostly older versions from conda-forge. Among them, qt is downgraded from 5.9.6 to 5.6.2. Check Spyder as before: it produces a Windows dialogue that says "Python has stopped working".

  6. Roll back to the revision before nco was installed with: conda install --revision <previous_revision>. All OK now.

I'm no expert on Conda packages (though I hope to start producing one soon, so I'd better learn!) However I think nco's dependency information is broken, probably too strict about allowing new versions.

**Comment by xylar** [comment]
I don't have a Windows setup to experiment with (I use Linux exclusively) but I tried installing spyder 3.3.1 along with both nco 4.7.6 and 4.7.5, and spyder worked fine in linux with both.  It may be that this is a strictly Windows issue, then.  It could also be that my setup is slightly different from @hadfieldnz's.  I had miniconda3 already installed and simply created new environments with python=3.6, spyder, xarray eofs, cartopy and netcd4.  I verified that spyder worked, then installed one or the other version of nco and verified that spyder still worked.

**Comment by ocefpaf** [comment]
> This may relate to the fact that the windows build failed for nco 4.7.6 and in could be that the windows build of 4.7.5 is out of sync with the current conda-forge pinnings.

Not really. It is probably more related to issues with latest conda. See https://github.com/conda/conda/issues/7656 and https://github.com/conda/conda/issues/7626 which affects features (that are heavily used on Windows).

If you can remove `defaults` and try a solution with only `conda-forge` it may work, or at least give us a meaningful error to work with.

PS: the `conda` slowness to resolve packages is being addressed but meanwhile ~5 min waits are the norm :-(

**Comment by hadfieldnz** [comment]
I appear to have fixed the problem by setting "featureless_minimization_disabled_feature_flag: true" in .condarc before installing nco ([conda/conda#7626](https://github.com/conda/conda/issues/7626)). Thank you.

PS: yes, conda is slow to resolve packages, but the wait of several minutes to install nco was clearly related to the large number of packages that was being downgraded. It's much faster now.

**Comment by hadfieldnz** [comment]
I have now taken the time to read to the end of issue 7626 and realised that "featureless_minimization_disabled_feature_flag: true" is not the complete solution it was intended to be. I shall await further developments with interest. In the meantime, I can report that removing the defaults channel from ~/.condarc before installing nco also fixed the spyder breakage problem.

Is there any good reason why I should not remove the defaults channel permanently?

**Comment by ocefpaf** [comment]
> Is there any good reason why I should not remove the defaults channel permanently?

I am biased :grimacing: but my answer is that there is no good reason. However, https://github.com/conda/conda/issues/7656 should be the best way to go and your :+1: there will help the conda devs prioritize that issue.

**Comment by xylar** [comment]
I'm going to close this because i think it's not an issue that can be addressed directly in this feedstock.  Feel free to re-open if you disagree.
