### ISSUE TITLE
Appveyor windows builds fail for two reasons

### ISSUE THREAD

**Issue by czender** [conda-forge/nco-feedstock#83]
Pinging @xylar @ocefpaf @pedro-vicente

Windows builds of NCO 4.7.9-alphaXXX have been failing for (I think) two reasons. I am trying to fix one related to the handling of the new netCDF memio structure in netCDF 4.6.2, but Appveyor fails before it even tries to build the code with:

```
...
conda activate TEST
conda.exe info --all
'conda.exe' is not recognized as an internal or external command,
operable program or batch file.
Command exited with code 1
```
Full Appveyor output is available for any recent build e.g., https://ci.appveyor.com/project/czender/nco/builds/22375621

It's too difficult for me to fix the other Windows build issue (which is due to NCO with netCDF 4.6.2) until Appveyor gets fixed enough to start building the NCO source code (because I don't have Windows so I rely on Appveyor to test my modifications).

**Comment by ocefpaf** [comment]
I believe you are referring to failures in https://github.com/nco/nco, right? I can take a look in a moment.
