### ISSUE TITLE
Unexpected and prolonged Appveyor breakage

### ISSUE THREAD

**Issue by czender** [conda-forge/nco-feedstock#92]
I do not understand why Appveyor testing of NCO broke with build [1.0.854](https://ci.appveyor.com/project/czender/nco/builds/24947244) about 5 days ago.
Until then it had be working smoothly for a few weeks. Build 854 altered nothing to do with Appveyor. The breakage is caused by a **huge** number of packages that are suddenly unavailable in the channels NCO employs
```
PackagesNotFoundError: The following packages are not available from current channels:
  - libnetcdf -> bzip2[version='>=1.0.6,<2.0a0'] -> vc=9
  - libnetcdf -> curl[version='>=7.64.1,<8.0a0'] -> krb5[version='>=1.16.3,<1.17.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a']
  - libnetcdf -> curl[version='>=7.64.1,<8.0a0'] -> krb5[version='>=1.16.3,<1.17.0a0'] -> tk[version='>=8.6.9,<8.7.0a0']
...
```
and here are NCO's current channels 
```
Current channels:
  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
```
It's almost like a channel got renamed upstream and not propagated to our feedstock. However, I do not see any difference in the channels between the broken build 854 and the previous successful build [853](https://ci.appveyor.com/project/czender/nco/builds/24920453). In any case, I'm stumped, and need to bring it to the attention of others who may understand this unexpected behavior by Appveyor.

**Comment by ocefpaf** [comment]
@czender this breakage is in the `nco` repository, right? While there is an overlap of the people who take care of `nco`'s Appveyor testing there and the people working on the conda-forge `nco` package let's open an issue there. (PS: I believe I know what it is, PR to fix it soon...)

**Comment by czender** [comment]
Okey dokey. Glad you have a hunch as to the problem.
